---
dependencies: []

galaxy_info:
  author: scorputty
  description: RedHat/CentOS configuration for Packer.
  company: "N/A"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
      - 6
      - 7
  galaxy_tags:
    - cloud
    - system
    - packaging
    - development
