---

- name: Get the current kernel release.
  command: uname -r
  changed_when: false
  register: kernel_release

- name: Ensure necessary packages are installed.
  yum: "name={{ item }} state=present"
  with_items:
    - bzip2
    - cpp
    - curl
    - gcc
    - kernel-devel
    - "kernel-devel-{{ kernel_release.stdout }}"
    - kernel-headers
    - libselinux-python
    - make
    - net-tools
    - ntp
    - openssh-clients
    - openssl-devel
    - readline-devel
    - rsync
    - sudo
    - vim
    - wget
    - yum-utils
    - zlib-devel

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf

- name: Ensure NTP is running and enabled as configured.
  service:
    name: ntpd
    state: started
    enabled: yes

# Fix slow DNS.
- name: Fix slow DNS (adapted from Bento).
  lineinfile:
    dest: /etc/sysconfig/network
    regexp: '^RES_OPTIONS'
    line: 'RES_OPTIONS="single-request-reopen"'
    state: present

# Fix ifcfg-lo errors
- name: Bug fixing network loopback
  command: echo "NM_CONTROLLED=no" >>/etc/sysconfig/network-scripts/ifcfg-lo

- name: Restart network service (explicitly).
  service: name=network state=restarted

# SSH daemon configuration.
- name: Configure SSH daemon.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^UseDNS', line: 'UseDNS no' }
    - { regexp: '^GSSAPIAuthentication', line: 'GSSAPIAuthentication no' }

# Vagrant SSH configuration.
- name: Configure Vagrant .ssh directory.
  file:
    path: /home/vagrant/.ssh
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0700

- name: Get Vagrant's public key.
  get_url:
    url: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
    dest: /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    group: vagrant
    mode: 0600

# VirtualBox tools installation.
- name: Check if VirtualBox is running the guest VM.
  stat: path=/home/vagrant/.vbox_version
  register: virtualbox_check

- include: virtualbox.yml
  when: virtualbox_check.stat.exists

# Cleanup tasks.
- name: Remove unneeded packages.
  yum: "name={{ item }} state=absent"
  with_items:
    - "alsa-*"
    - "*firmware*"
    - "b43-openfwwf"
    - "wpa_supplicant"
    - "plymouth*"
    - "perl*"

- name: Remove surplus kernels
  command: package-cleanup -y --oldkernels --count=1

- name: Clean up yum.
  command: yum clean all

- name: Remove files
  file: name="{{ item }}" state=absent
  with_items:
    - /etc/udev/rules.d/70-persistent-net.rules
    - VBoxGuestAdditions_*.iso
    - VBoxGuestAdditions_*.iso.?

- name: Clean yum caches
  file:
    state: absent
    path: "/var/cache/yum/x86_64/"

- name: Remove RedHat interface persistence.
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: "{{ item }}"
    state: absent
  with_items:
    - '^HWADDR'
    - '^UUID'

- name: System tuning
  shell: echo "vm.dirty_background_bytes=100000000" >> /etc/sysctl.conf

- name: Disable unnecessary services
  service: name="{{ item }}" state=stopped enabled=no
  with_items:
    - kdump
