---
  # Install packages
  - name: Get the current kernel release.
    command: uname -r
    changed_when: false
    register: kernel_release

  - name: Ensure necessary packages are installed.
    yum: "name={{ item }} state=present"
    with_items:
      - bzip2
      - cpp
      - curl
      - gcc
      - "kernel-devel-{{ kernel_release.stdout }}"
      - kernel-headers
      - libselinux-python
      - make
      - net-tools
      - NetworkManager
      - ntp
      - openssh-clients
      - openssl-devel
      - readline-devel
      - rsync
      - sudo
      - vim
      - wget
      - yum-utils
      - zlib-devel

  # check if it's VirtualBox
  - name: Check if VirtualBox of QEMU
    command: sudo dmidecode -s | egrep -i 'vendor'
    register: command_result

  - name: check result dmidecode |
    debug: msg="{{ command_result.stdout }}"

  # Install GuestAdditions (ignore errors for qemu)
  - include: vboxguestadditions.yml
    when: not "'QEMU' in command_result.stdout"
    ignore_errors: yes

  # Fixes
  - name: Fix slow DNS (adapted from Bento).
    lineinfile:
      dest: /etc/sysconfig/network
      regexp: '^RES_OPTIONS'
      line: 'RES_OPTIONS="single-request-reopen"'
      state: present

  - name: Fixing ifcfg-lo errors network loopback
    command: echo "NM_CONTROLLED=no" >>/etc/sysconfig/network-scripts/ifcfg-lo

  - name: Fix yum SSL errors
    command: yum -y reinstall ca-certificates openssl

  - name: Remove RedHat interface persistence.
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      regexp: "{{ item }}"
      state: absent
    with_items:
      - '^HWADDR'
      - '^UUID'

  - name: System tuning
    shell: echo "vm.dirty_background_bytes=100000000" >> /etc/sysctl.conf

  - name: Disable unnecessary services
    systemd: name="{{ item }}" state=stopped enabled=no
    with_items:
      - kdump

  # - name: Restart network service (explicitly).
  #   service: name=network state=restarted

  # Setup time
  - name: Set timezone
    timezone:
      name: "{{ timezone }}"

  - name: Copy the ntp.conf template file
    template: src=ntp.conf.j2 dest=/etc/ntp.conf

  - name: Ensure NTP is running and enabled as configured.
    systemd:
      name: ntpd
      state: started
      enabled: yes

  # SSH daemon configuration.
  - name: Configure SSH daemon.
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - { regexp: '^UseDNS', line: 'UseDNS no' }
      - { regexp: '^GSSAPIAuthentication', line: 'GSSAPIAuthentication no' }

  # Vagrant SSH configuration.
  - name: Get Vagrants public key.
    authorized_key:
      user: vagrant
      key: https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub
      validate_certs: no

  # Cleanup tasks.
  - name: Remove unneeded packages.
    yum: "name={{ item }} state=absent"
    with_items:
      - "alsa-*"
      - "iwl*firmware"
      - "b43-openfwwf"
      - "plymouth*"

  - name: Remove surplus kernels
    command: package-cleanup -y --oldkernels --count=1

  - name: Clean up yum.
    command: yum clean all

  - name: Remove files
    file: name="{{ item }}" state=absent
    with_items:
      - /etc/udev/rules.d/70-persistent-net.rules
